### ISSUE TITLE
preserve at-exp syntax coloring?

### ISSUE THREAD

**Issue by mbutterick** [jeapostrophe/remix#22]
`#lang remix` invokes the at-reader by default. But one still needs to put `at-exp` in the `#lang` line to get the syntax coloring to behave correctly within at-expressions, otherwise certain characters like `|` will foul it up:

![screen shot 2018-06-07 at jun 07 12 17 47 pm](https://user-images.githubusercontent.com/1425051/41121290-cfbc7562-6a4c-11e8-931b-348d0dd69888.gif)

![screen shot 2018-06-07 at jun 07 12 17 40 pm](https://user-images.githubusercontent.com/1425051/41121287-ce81c6f2-6a4c-11e8-95e5-87668e0270d5.gif)

**Comment by jeapostrophe** [comment]
Just fixed in the recent push. Thanks for the report!
